export interface BizConfig {
  biz_key: string
  name: string
  tagline: string
  description: string
  primaryColor: string
  accentColor: string
  offer: string
  leadType: string
  ctaLabel: string
  formFields: ('phone' | 'company' | 'role' | 'message')[]
  thankYouMsg: string
  benefits: string[]
}

const configs: Record<string, BizConfig> = {
  'aquame': { biz_key:'aquame', name:'AquaMe', leadType:'enquiry', tagline:'Smart Water Intelligence', primaryColor:'#0ea5e9', accentColor:'#0284c7', description:'AI-powered water monitoring and optimisation for residential and commercial properties.', offer:'Free Water Audit', ctaLabel:'Book Free Audit', formFields:['phone','company','message'], thankYouMsg:"Thanks! We'll be in touch within 4 hours to book your free water audit.", benefits:['Real-time monitoring','Leak detection','Usage analytics','Cost reduction'] },
  'medledger': { biz_key:'medledger', name:'MedLedger', leadType:'demo', tagline:'Healthcare Financial Clarity', primaryColor:'#10b981', accentColor:'#059669', description:'Blockchain-verified financial records and compliance automation for healthcare providers.', offer:'Free Compliance Demo', ctaLabel:'Request Demo', formFields:['phone','company','role','message'], thankYouMsg:'Demo request received. Our team will contact you within 4 business hours.', benefits:['Audit-ready records','Compliance automation','Real-time reporting','Secure & verified'] },
  'mission-critical': { biz_key:'mission-critical', name:'Mission Critical', leadType:'enquiry', tagline:'When Failure Is Not An Option', primaryColor:'#ef4444', accentColor:'#dc2626', description:'Enterprise resilience and continuity planning powered by AI risk intelligence.', offer:'Free Risk Assessment', ctaLabel:'Get Risk Assessment', formFields:['phone','company','role','message'], thankYouMsg:"Risk assessment request received. We'll respond within 2 business hours.", benefits:['99.99% uptime design','AI risk modelling','Rapid incident response','Continuity planning'] },
  'outcome-ready': { biz_key:'outcome-ready', name:'Outcome Ready', leadType:'pilot', tagline:'NDIS Outcomes. Delivered.', primaryColor:'#8b5cf6', accentColor:'#7c3aed', description:'AI-driven NDIS participant management and outcome tracking platform.', offer:'Free 30-Day Pilot', ctaLabel:'Start Free Pilot', formFields:['phone','company','role','message'], thankYouMsg:"Pilot request received! We'll set up your account within 24 hours.", benefits:['NDIS compliant','Outcome tracking','Progress reporting','Participant portal'] },
  'smartpark': { biz_key:'smartpark', name:'SmartPark', leadType:'demo', tagline:'Intelligent Parking. Zero Friction.', primaryColor:'#f59e0b', accentColor:'#d97706', description:'AI-powered parking management and revenue optimisation for operators and councils.', offer:'Free Parking Audit', ctaLabel:'Book Parking Audit', formFields:['phone','company','message'], thankYouMsg:"Audit request received. We'll contact you within 24 hours.", benefits:['Real-time availability','Dynamic pricing','Revenue uplift','Council reporting'] },
  'apac-just-walk-out': { biz_key:'apac-just-walk-out', name:'APAC Just Walk Out', leadType:'demo', tagline:'Frictionless Retail for APAC', primaryColor:'#06b6d4', accentColor:'#0891b2', description:'Amazon-style cashierless checkout technology for APAC retailers.', offer:'Free Store Assessment', ctaLabel:'Request Assessment', formFields:['phone','company','role','message'], thankYouMsg:"Assessment request received. Our retail team will be in touch within 4 hours.", benefits:['Zero checkout queues','AI computer vision','Seamless payments','Proven ROI'] },
  'justpoint': { biz_key:'justpoint', name:'JustPoint', leadType:'enquiry', tagline:'Loyalty That Actually Works', primaryColor:'#ec4899', accentColor:'#db2777', description:'Next-gen loyalty and rewards platform with AI personalisation.', offer:'Free Loyalty Audit', ctaLabel:'Get Loyalty Audit', formFields:['phone','company','message'], thankYouMsg:"Thanks! Expect a call within 24 hours to discuss your loyalty strategy.", benefits:['AI personalisation','Multi-channel rewards','Real-time analytics','Easy integration'] },
  'xces': { biz_key:'xces', name:'XCES', leadType:'demo', tagline:'Excess Inventory. Solved.', primaryColor:'#6366f1', accentColor:'#4f46e5', description:'AI marketplace for excess inventory liquidation and supply chain optimisation.', offer:'Free Inventory Analysis', ctaLabel:'Analyse My Inventory', formFields:['phone','company','role','message'], thankYouMsg:"Analysis request received. We'll have insights for you within 24 hours.", benefits:['Instant liquidity','AI matching','Global buyers','Zero waste target'] },
  'ai-olympics': { biz_key:'ai-olympics', name:'AI Olympics', leadType:'registration', tagline:'Compete. Learn. Win.', primaryColor:'#f97316', accentColor:'#ea580c', description:'Global AI competition platform measuring human-AI collaboration performance.', offer:'Free Entry Registration', ctaLabel:'Register Now', formFields:['phone','company','message'], thankYouMsg:'Registration received! Check your email for competition details.', benefits:['Global leaderboard','Cash prizes','AI performance metrics','Skills certification'] },
  'consentx': { biz_key:'consentx', name:'ConsentX', leadType:'demo', tagline:'Consent. Compliant. Clear.', primaryColor:'#14b8a6', accentColor:'#0d9488', description:'AI-powered consent management platform for healthcare and financial services.', offer:'Free Compliance Check', ctaLabel:'Get Compliance Check', formFields:['phone','company','role','message'], thankYouMsg:"Compliance check request received. Our team will contact you within 4 hours.", benefits:['GDPR & HIPAA ready','Audit trail','Digital consent flows','Real-time verification'] },
  'gc-bat-core': { biz_key:'gc-bat-core', name:'GC-BAT Core', leadType:'enquiry', tagline:'Gold Coast Business Acceleration', primaryColor:'#eab308', accentColor:'#ca8a04', description:'AI business acceleration and transformation program for Gold Coast enterprises.', offer:'Free Acceleration Workshop', ctaLabel:'Book Workshop', formFields:['phone','company','role','message'], thankYouMsg:"Workshop request received. We'll confirm your spot within 24 hours.", benefits:['AI readiness assessment','Growth roadmap','Expert mentoring','Peer network'] },
  'lifegraph-plus': { biz_key:'lifegraph-plus', name:'LifeGraph Plus', leadType:'trial', tagline:'Your Life. Mapped. Optimised.', primaryColor:'#a855f7', accentColor:'#9333ea', description:'Personal AI that maps your life data to predict, optimise, and accelerate your goals.', offer:'Free 14-Day Trial', ctaLabel:'Start Free Trial', formFields:['phone','message'], thankYouMsg:'Trial activated! Check your email for access instructions.', benefits:['Life pattern AI','Goal tracking','Health integration','Daily insights'] },
  'myneruralsignal': { biz_key:'myneruralsignal', name:'MyNeuralSignal', leadType:'assessment', tagline:'Understand Your Brain. Unlock Your Potential.', primaryColor:'#3b82f6', accentColor:'#2563eb', description:'Neurodiversity assessment and AI coaching platform for individuals and organisations.', offer:'Free Neural Assessment', ctaLabel:'Start Assessment', formFields:['phone','company','message'], thankYouMsg:"Assessment started! We'll send your personalised report within 48 hours.", benefits:['ADHD & neurodiversity insights','AI coaching','Workplace optimisation','Evidence-based'] },
  'ratpak': { biz_key:'ratpak', name:'RATPAK', leadType:'enquiry', tagline:'Research. Analyse. Transform.', primaryColor:'#64748b', accentColor:'#475569', description:'AI research intelligence and competitive analysis platform for strategy teams.', offer:'Free Intelligence Briefing', ctaLabel:'Get Intelligence Briefing', formFields:['phone','company','role','message'], thankYouMsg:"Briefing request received. Your intelligence pack will be ready within 24 hours.", benefits:['Real-time market signals','Competitor tracking','AI synthesis','Executive reports'] }
}

export function getBizConfig(): BizConfig {
  const key = process.env.NEXT_PUBLIC_BIZ_KEY || 'aquame'
  return configs[key] || configs['aquame']
}

export default configs
